
package project_restaurant.view;

import java.awt.event.ActionListener;

public class AccessButtonsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccessButtonsPanel
     */
    public AccessButtonsPanel() {
        initComponents();
    }
    
    //METODO ACTION LISTENER
    public void listen (ActionListener controller){
        btnSignIn.addActionListener(controller);
        btnSignUp.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();

        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton sign in.png"))); // NOI18N
        btnSignIn.setActionCommand("Sign-In");
        btnSignIn.setBorderPainted(false);
        btnSignIn.setContentAreaFilled(false);
        btnSignIn.setMaximumSize(new java.awt.Dimension(378, 67));
        btnSignIn.setMinimumSize(new java.awt.Dimension(378, 67));

        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton sign up.png"))); // NOI18N
        btnSignUp.setActionCommand("Sign-Up");
        btnSignUp.setBorderPainted(false);
        btnSignUp.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnSignUp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnSignUp)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    // End of variables declaration//GEN-END:variables
}
