/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_restaurant.view;

/**
 *
 * @author fcama
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }
    
    public LoginButtonsPanel loginButtonsPanel(){
        return loginButtonsPanel;
    }
    
    public LoginDataPanel loginDataPanel(){
        return loginDataPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginDataPanel = new project_restaurant.view.LoginDataPanel();
        loginButtonsPanel = new project_restaurant.view.LoginButtonsPanel();
        login_fondo_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginDataPanel.setOpaque(false);
        getContentPane().add(loginDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 390, 300));

        loginButtonsPanel.setOpaque(false);
        getContentPane().add(loginButtonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, -1));

        login_fondo_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo rojo base.png"))); // NOI18N
        getContentPane().add(login_fondo_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project_restaurant.view.LoginButtonsPanel loginButtonsPanel;
    private project_restaurant.view.LoginDataPanel loginDataPanel;
    private javax.swing.JLabel login_fondo_img;
    // End of variables declaration//GEN-END:variables
}
