/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_restaurant.view;

import javax.swing.JPasswordField;
import javax.swing.JTextField;
import project_restaurant.controller.*;

/**
 *
 * @author fcama
 */
public class RegisterDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterDataPanel
     */
    public RegisterDataPanel() {
        initComponents();
    }
    
    //METODOS SET Y GET 
    public String getTxtEmail() {
        return txtEmail.getText();
    }

    public void setTxtEmail(String txtEmail) {
        this.txtEmail.setText(txtEmail);
    }

    public String getTxtPasswordRegister() {
        return txtPasswordRegister.toString();
    }

    public void setTxtPasswordRegister(String txtPasswordRegister) {
        this.txtPasswordRegister.setText(txtPasswordRegister);
    }

    public String getTxtUserNameRegister() {
        return txtUserNameRegister.getText();
    }

    public void setTxtUserNameRegister(String txtUserNameRegister) {
        this.txtUserNameRegister.setText(txtUserNameRegister);
    }
    
    public void listen(CustomerRegisterController controller){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserNameRegister = new javax.swing.JTextField();
        txtPasswordRegister = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 129, 45));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 158, 129, 43));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 313, 109, 36));

        txtUserNameRegister.setBackground(new java.awt.Color(245, 245, 245));
        txtUserNameRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserNameRegister.setForeground(new java.awt.Color(45, 45, 45));
        txtUserNameRegister.setBorder(null);
        add(txtUserNameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 40));

        txtPasswordRegister.setBackground(new java.awt.Color(245, 245, 245));
        txtPasswordRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPasswordRegister.setForeground(new java.awt.Color(45, 45, 45));
        txtPasswordRegister.setBorder(null);
        add(txtPasswordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 350, 40));

        txtEmail.setBackground(new java.awt.Color(245, 245, 245));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(45, 45, 45));
        txtEmail.setBorder(null);
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 350, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra1-5px.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra1-5px.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra1-5px.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPasswordRegister;
    private javax.swing.JTextField txtUserNameRegister;
    // End of variables declaration//GEN-END:variables
}
