/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_restaurant.view;

/**
 *
 * @author fcama
 */
public class RegisterGUI extends javax.swing.JPanel {

    /**
     * Creates new form RegisterGUI
     */
    public RegisterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerButtonsPanel = new project_restaurant.view.RegisterButtonsPanel();
        registerDataPanel = new project_restaurant.view.RegisterDataPanel();
        fondoRegistro = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerButtonsPanel.setOpaque(false);
        add(registerButtonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, -1, -1));

        registerDataPanel.setOpaque(false);
        add(registerDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 400, 430));

        fondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo rojo base.png"))); // NOI18N
        add(fondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoRegistro;
    private project_restaurant.view.RegisterButtonsPanel registerButtonsPanel;
    private project_restaurant.view.RegisterDataPanel registerDataPanel;
    // End of variables declaration//GEN-END:variables
}
