/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_restaurant.view;

import project_restaurant.controller.CustomerRegisterController;

/**
 *
 * @author fcama
 */
public class RegisterGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegisterGUI
     */
    public RegisterGUI() {
        initComponents();
    }
    
    
    public RegisterButtonsPanel registerButtonsPanel(){
        return registerButtonsPanel;
    }
    
    public RegisterDataPanel registerDataPanel(){
        return registerDataPanel;
    }
    
    public void listen(CustomerRegisterController controller){
        registerButtonsPanel.listen(controller);
        registerDataPanel.listen(controller);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerButtonsPanel = new project_restaurant.view.RegisterButtonsPanel();
        registerDataPanel = new project_restaurant.view.RegisterDataPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerButtonsPanel.setOpaque(false);
        getContentPane().add(registerButtonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, -1));

        registerDataPanel.setOpaque(false);
        getContentPane().add(registerDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 390, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo rojo base.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private project_restaurant.view.RegisterButtonsPanel registerButtonsPanel;
    private project_restaurant.view.RegisterDataPanel registerDataPanel;
    // End of variables declaration//GEN-END:variables
}
