/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_restaurant.view.menu;

import java.awt.event.MouseListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import project_restaurant.model.*;

/**
 *
 * @author fcama
 */
public class AppetizerMenuGUI extends javax.swing.JFrame {

    private Food food;
    private AppetizerMenuGUI appetizerGUI;
    private BuyBottomPanel buyBottom;
    private PileFood pileFood;
    private NodeFood nodeFood;

    /**
     * Creates new form AppetizerMenuGUI
     */
    public AppetizerMenuGUI() {
        buyBottom = new BuyBottomPanel();
        pileFood = new PileFood();
        initComponents();
    }

    public NavMenuPanel getNavMenuPanel() {
        return navMenuPanel;
    }

    public String getLblNameO1() {
        return "Edamame";
    }

    public void setLblNameO1(String lblNameO1) {
        lblNameO1 = "Edamame";
    }

    public String getLblPriceO1() {
        return "$5";
    }

    public void setLblPriceO1(String lblPriceO1) {
        lblPriceO1 = "$5";
    }

    public String getLblNameO2() {
        return "Gyoza";
    }

    public void setLblNameO2(String lblNameO2) {
        lblNameO2 = "Gyoza";
    }

    public String getLblPriceO2() {
        return "$10";
    }

    public void setLblPriceO2(String lblPriceO2) {
        lblPriceO2 = "$10";
    }

    public String getLblNameO3() {
        return "Yakitori";
    }

    public void setLblNameO3(String lblNameO3) {
        lblNameO3 = "Yakitori";
    }

    public String getLblNameO4() {
        return "Tempura";
    }

    public void setLblNameO4(String lblNameO4) {
        lblNameO4 = "Tempura";
    }

    public String getLblNameO5() {
        return "Sunomono";
    }

    public void setLblNameO5(String lblNameO5) {
        lblNameO5 = "Sunomono";
    }

    public String getLblNameO6() {
        return "Takoyaki";
    }

    public void setLblNameO6(String lblNameO6) {
        lblNameO6 = "Takoyaki";
    }

    public String getLblPriceO3() {
        return "$8";
    }

    public void setLblPriceO3(String lblPriceO3) {
        lblPriceO3 = "$8";
    }

    public String getLblPriceO4() {
        return "$7";
    }

    public void setLblPriceO4(String lblPriceO4) {
        lblPriceO4 = "$7";
    }

    public String getLblPriceO5() {
        return "$9";
    }

    public void setLblPriceO5(String lblPriceO5) {
        lblPriceO5 = "$9";
    }

    public String getLblPriceO6() {
        return "$11";
    }

    public void setLblPriceO6(String lblPriceO6) {
        lblPriceO6 = "$11";
    }

    public String getLblNameO7() {
        return "Ebi Mayo";
    }

    public void setLblNameO7(String lblNameO7) {
        lblNameO7 = "Ebi Mayo";
    }

    public String getLblPriceO7() {
        return "$8";
    }

    public void setLblPriceO7(String lblPriceO7) {
        lblPriceO7 = "$8";
    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        buyBottomPanel1 = new project_restaurant.view.menu.BuyBottomPanel();
        navMenuPanel = new project_restaurant.view.menu.NavMenuPanel();
        lblNameO7 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblPriceO7 = new javax.swing.JLabel();
        lblNameO6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblPriceO6 = new javax.swing.JLabel();
        lblNameO5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblPriceO5 = new javax.swing.JLabel();
        lblNameO4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblPriceO4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblNameO3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPriceO3 = new javax.swing.JLabel();
        lblNameO2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPriceO2 = new javax.swing.JLabel();
        lblPriceO1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNameO1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buyBottomPanel2 = new project_restaurant.view.menu.BuyBottomPanel();
        buyBottomPanel3 = new project_restaurant.view.menu.BuyBottomPanel();
        buyBottomPanel4 = new project_restaurant.view.menu.BuyBottomPanel();
        buyBottomPanel5 = new project_restaurant.view.menu.BuyBottomPanel();
        buyBottomPanel6 = new project_restaurant.view.menu.BuyBottomPanel();
        buyBottomPanel7 = new project_restaurant.view.menu.BuyBottomPanel();
        Edamame = new project_restaurant.view.menu.ObjectDishPanel();
        Gyoza = new project_restaurant.view.menu.ObjectDishPanel();
        Yakitori = new project_restaurant.view.menu.ObjectDishPanel();
        Tempura = new project_restaurant.view.menu.ObjectDishPanel();
        Sunomono = new project_restaurant.view.menu.ObjectDishPanel();
        Takoyaki = new project_restaurant.view.menu.ObjectDishPanel();
        EbiMayo = new project_restaurant.view.menu.ObjectDishPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buyBottomPanel1.setOpaque(false);
        buyBottomPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBottomPanel1MouseClicked(evt);
            }
        });
        jPanel2.add(buyBottomPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));
        jPanel2.add(navMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        lblNameO7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNameO7.setForeground(new java.awt.Color(51, 51, 51));
        lblNameO7.setText("Ebi Mayo");
        jPanel2.add(lblNameO7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1350, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Appetizer");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1380, -1, -1));

        lblPriceO7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceO7.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceO7.setText("$8");
        jPanel2.add(lblPriceO7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1410, -1, -1));

        lblNameO6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNameO6.setForeground(new java.awt.Color(51, 51, 51));
        lblNameO6.setText("Takoyaki");
        jPanel2.add(lblNameO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1140, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Appetizer");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1170, -1, -1));

        lblPriceO6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceO6.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceO6.setText("$11");
        jPanel2.add(lblPriceO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1200, -1, -1));

        lblNameO5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNameO5.setForeground(new java.awt.Color(51, 51, 51));
        lblNameO5.setText("Sunomono");
        jPanel2.add(lblNameO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 930, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Appetizer");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 960, -1, -1));

        lblPriceO5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceO5.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceO5.setText("$9");
        jPanel2.add(lblPriceO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 990, -1, -1));

        lblNameO4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNameO4.setForeground(new java.awt.Color(51, 51, 51));
        lblNameO4.setText("Tempura");
        jPanel2.add(lblNameO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 720, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Appetizer");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 750, -1, -1));

        lblPriceO4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceO4.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceO4.setText("$7");
        jPanel2.add(lblPriceO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 780, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ebi-Mayo.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1340, 220, 190));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/takoyaki.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1130, 220, 190));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sunomono.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 920, 220, 190));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tempura (1).png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 220, 190));

        lblNameO3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNameO3.setForeground(new java.awt.Color(51, 51, 51));
        lblNameO3.setText("Yakitori");
        jPanel2.add(lblNameO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Appetizer");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        lblPriceO3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceO3.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceO3.setText("$8");
        jPanel2.add(lblPriceO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        lblNameO2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNameO2.setForeground(new java.awt.Color(51, 51, 51));
        lblNameO2.setText("Gyoza");
        jPanel2.add(lblNameO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Appetizer");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        lblPriceO2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceO2.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceO2.setText("$10");
        jPanel2.add(lblPriceO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        lblPriceO1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceO1.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceO1.setText("$5");
        jPanel2.add(lblPriceO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Appetizer");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        lblNameO1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNameO1.setForeground(new java.awt.Color(51, 51, 51));
        lblNameO1.setText("Edamame");
        jPanel2.add(lblNameO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edamame.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Yakitori.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 220, 190));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prawn-gyoza.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 190));

        buyBottomPanel2.setOpaque(false);
        buyBottomPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBottomPanel2MouseClicked(evt);
            }
        });
        jPanel2.add(buyBottomPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        buyBottomPanel3.setOpaque(false);
        buyBottomPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBottomPanel3MouseClicked(evt);
            }
        });
        jPanel2.add(buyBottomPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, -1, -1));

        buyBottomPanel4.setOpaque(false);
        buyBottomPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBottomPanel4MouseClicked(evt);
            }
        });
        jPanel2.add(buyBottomPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 840, -1, -1));

        buyBottomPanel5.setOpaque(false);
        buyBottomPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBottomPanel5MouseClicked(evt);
            }
        });
        jPanel2.add(buyBottomPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1050, -1, -1));

        buyBottomPanel6.setOpaque(false);
        buyBottomPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBottomPanel6MouseClicked(evt);
            }
        });
        jPanel2.add(buyBottomPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1260, -1, -1));

        buyBottomPanel7.setOpaque(false);
        buyBottomPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBottomPanel7MouseClicked(evt);
            }
        });
        jPanel2.add(buyBottomPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1470, -1, -1));
        jPanel2.add(Edamame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel2.add(Gyoza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel2.add(Yakitori, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));
        jPanel2.add(Tempura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, -1, -1));
        jPanel2.add(Sunomono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 910, -1, -1));
        jPanel2.add(Takoyaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1120, -1, -1));
        jPanel2.add(EbiMayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1330, -1, -1));

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 1570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyBottomPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBottomPanel1MouseClicked

        appetizerGUI = new AppetizerMenuGUI();
        String name = appetizerGUI.getLblNameO1();
        String price = appetizerGUI.getLblPriceO1();

        food = new Food(name, price);
        pileFood.push(food);
        System.out.println("Platillo registrado con éxito");
        showMessage(pileFood.toString());
        System.out.println(pileFood.toString());    }//GEN-LAST:event_buyBottomPanel1MouseClicked

    private void buyBottomPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBottomPanel2MouseClicked
        appetizerGUI = new AppetizerMenuGUI();
        String name = appetizerGUI.getLblNameO2();
        String price = appetizerGUI.getLblPriceO2();

        food = new Food(name, price);
        pileFood.push(food);
        System.out.println("Platillo registrado con éxito");
        showMessage(pileFood.toString());
        System.out.println(pileFood.toString());    }//GEN-LAST:event_buyBottomPanel2MouseClicked

    private void buyBottomPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBottomPanel3MouseClicked
        appetizerGUI = new AppetizerMenuGUI();
        String name = appetizerGUI.getLblNameO3();
        String price = appetizerGUI.getLblPriceO3();

        food = new Food(name, price);
        pileFood.push(food);
        System.out.println("Platillo registrado con éxito");
        showMessage(pileFood.toString());
        System.out.println(pileFood.toString());    }//GEN-LAST:event_buyBottomPanel3MouseClicked

    private void buyBottomPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBottomPanel4MouseClicked
        appetizerGUI = new AppetizerMenuGUI();
        String name = appetizerGUI.getLblNameO4();
        String price = appetizerGUI.getLblPriceO4();

        food = new Food(name, price);
        pileFood.push(food);
        System.out.println("Platillo registrado con éxito");
        showMessage(pileFood.toString());
        System.out.println(pileFood.toString());    }//GEN-LAST:event_buyBottomPanel4MouseClicked

    private void buyBottomPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBottomPanel5MouseClicked
        appetizerGUI = new AppetizerMenuGUI();
        String name = appetizerGUI.getLblNameO5();
        String price = appetizerGUI.getLblPriceO5();

        food = new Food(name, price);
        pileFood.push(food);
        System.out.println("Platillo registrado con éxito");
        showMessage(pileFood.toString());
        System.out.println(pileFood.toString());    }//GEN-LAST:event_buyBottomPanel5MouseClicked

    private void buyBottomPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBottomPanel6MouseClicked
        appetizerGUI = new AppetizerMenuGUI();
        String name = appetizerGUI.getLblNameO6();
        String price = appetizerGUI.getLblPriceO6();

        food = new Food(name, price);
        pileFood.push(food);
        System.out.println("Platillo registrado con éxito");
        showMessage(pileFood.toString());
        System.out.println(pileFood.toString());    }//GEN-LAST:event_buyBottomPanel6MouseClicked

    private void buyBottomPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBottomPanel7MouseClicked
        appetizerGUI = new AppetizerMenuGUI();
        String name = appetizerGUI.getLblNameO7();
        String price = appetizerGUI.getLblPriceO7();

        food = new Food(name, price);
        pileFood.push(food);
        System.out.println("Platillo registrado con éxito");
        showMessage(pileFood.toString());
        System.out.println(pileFood.toString());    }//GEN-LAST:event_buyBottomPanel7MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project_restaurant.view.menu.ObjectDishPanel EbiMayo;
    private project_restaurant.view.menu.ObjectDishPanel Edamame;
    private project_restaurant.view.menu.ObjectDishPanel Gyoza;
    private project_restaurant.view.menu.ObjectDishPanel Sunomono;
    private project_restaurant.view.menu.ObjectDishPanel Takoyaki;
    private project_restaurant.view.menu.ObjectDishPanel Tempura;
    private project_restaurant.view.menu.ObjectDishPanel Yakitori;
    private project_restaurant.view.menu.BuyBottomPanel buyBottomPanel1;
    private project_restaurant.view.menu.BuyBottomPanel buyBottomPanel2;
    private project_restaurant.view.menu.BuyBottomPanel buyBottomPanel3;
    private project_restaurant.view.menu.BuyBottomPanel buyBottomPanel4;
    private project_restaurant.view.menu.BuyBottomPanel buyBottomPanel5;
    private project_restaurant.view.menu.BuyBottomPanel buyBottomPanel6;
    private project_restaurant.view.menu.BuyBottomPanel buyBottomPanel7;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNameO1;
    private javax.swing.JLabel lblNameO2;
    private javax.swing.JLabel lblNameO3;
    private javax.swing.JLabel lblNameO4;
    private javax.swing.JLabel lblNameO5;
    private javax.swing.JLabel lblNameO6;
    private javax.swing.JLabel lblNameO7;
    private javax.swing.JLabel lblPriceO1;
    private javax.swing.JLabel lblPriceO2;
    private javax.swing.JLabel lblPriceO3;
    private javax.swing.JLabel lblPriceO4;
    private javax.swing.JLabel lblPriceO5;
    private javax.swing.JLabel lblPriceO6;
    private javax.swing.JLabel lblPriceO7;
    private project_restaurant.view.menu.NavMenuPanel navMenuPanel;
    // End of variables declaration//GEN-END:variables
}
