/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_restaurant.view.menu;

import javax.swing.JLabel;
import project_restaurant.model.*;

/**
 *
 * @author fcama
 */
public class AppetizerMenuGUI extends javax.swing.JFrame {
    private Food food;
    private AppetizerMenuGUI appetizerGUI;
    private PileFood pileFood;
    private NodeFood nodeFood;
    /**
     * Creates new form AppetizerMenuGUI
     */
    public AppetizerMenuGUI() {
        pileFood = new PileFood();
        initComponents();
    }

    public NavMenuPanel getNavMenuPanel() {
        return navMenuPanel;
    }

    public String getLblNameO1() {
        return "Edamame";
    }

    public void setLblNameO1(String lblNameO1) {
        lblNameO1 = "Edamame";
    }

    public String getLblPriceO1() {
        return "$5";
    }

    public void setLblPriceO1(String lblPriceO1) {
        lblPriceO1 =  "$5";
    }

    public String getLblNameO2() {
        return "Gyoza";
    }

    public void setLblNameO2(String lblNameO2) {
        lblNameO2 = "Gyoza";
    }

    public String getLblPriceO2() {
        return "$10";
    }

    public void setLblPriceO2(String lblPriceO2) {
        lblPriceO2 = "$10";
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        navMenuPanel = new project_restaurant.view.menu.NavMenuPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblNameO2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPriceO2 = new javax.swing.JLabel();
        lblPriceO1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNameO1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buyBottomPanel1 = new project_restaurant.view.menu.BuyBottomPanel();
        buyBottomPanel2 = new project_restaurant.view.menu.BuyBottomPanel();
        Edamame = new project_restaurant.view.menu.ObjectDishPanel();
        Gyoza = new project_restaurant.view.menu.ObjectDishPanel();
        Yakitori = new project_restaurant.view.menu.ObjectDishPanel();
        Tempura = new project_restaurant.view.menu.ObjectDishPanel();
        Sunomono = new project_restaurant.view.menu.ObjectDishPanel();
        Takoyaki = new project_restaurant.view.menu.ObjectDishPanel();
        EbiMayo = new project_restaurant.view.menu.ObjectDishPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(navMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Ebi Mayo");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1350, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("H3");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1380, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("$000");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1410, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Takoyaki");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1140, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("H3");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1170, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("$000");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1200, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Sunomono");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 930, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("H3");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 960, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("$000");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 990, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Tempura");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 720, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("H3");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 750, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("$000");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 780, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ebi-Mayo.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1340, 220, 190));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/takoyaki.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1130, 220, 190));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sunomono.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 920, 220, 190));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tempura (1).png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 220, 190));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Yakitori");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("H3");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("$000");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        lblNameO2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNameO2.setForeground(new java.awt.Color(51, 51, 51));
        lblNameO2.setText("Gyoza");
        jPanel2.add(lblNameO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Appetizer");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        lblPriceO2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceO2.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceO2.setText("$10");
        jPanel2.add(lblPriceO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        lblPriceO1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceO1.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceO1.setText("$5");
        jPanel2.add(lblPriceO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Appetizer");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        lblNameO1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNameO1.setForeground(new java.awt.Color(51, 51, 51));
        lblNameO1.setText("Edamame");
        jPanel2.add(lblNameO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edamame.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Yakitori.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 220, 190));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prawn-gyoza.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 190));

        buyBottomPanel1.setOpaque(false);
        buyBottomPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBottomPanel1MouseClicked(evt);
            }
        });
        jPanel2.add(buyBottomPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        buyBottomPanel2.setOpaque(false);
        buyBottomPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBottomPanel2MouseClicked(evt);
            }
        });
        jPanel2.add(buyBottomPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));
        jPanel2.add(Edamame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel2.add(Gyoza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel2.add(Yakitori, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));
        jPanel2.add(Tempura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, -1, -1));
        jPanel2.add(Sunomono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 910, -1, -1));
        jPanel2.add(Takoyaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1120, -1, -1));
        jPanel2.add(EbiMayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1330, -1, -1));

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 1570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyBottomPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBottomPanel1MouseClicked
        appetizerGUI = new AppetizerMenuGUI();
        String name = appetizerGUI.getLblNameO1();
        String price = appetizerGUI.getLblPriceO1();

        food = new Food(name, price);
        pileFood.push(food);
        System.out.println("Platillo registrado con éxito");
        System.out.println(pileFood.toString());    }//GEN-LAST:event_buyBottomPanel1MouseClicked

    private void buyBottomPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBottomPanel2MouseClicked
        appetizerGUI = new AppetizerMenuGUI();
        String name = appetizerGUI.getLblNameO2();
        String price = appetizerGUI.getLblPriceO2();

        food = new Food(name, price);
        pileFood.push(food);
        System.out.println("Platillo registrado con éxito");
        System.out.println(pileFood.toString());    }//GEN-LAST:event_buyBottomPanel2MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project_restaurant.view.menu.ObjectDishPanel EbiMayo;
    private project_restaurant.view.menu.ObjectDishPanel Edamame;
    private project_restaurant.view.menu.ObjectDishPanel Gyoza;
    private project_restaurant.view.menu.ObjectDishPanel Sunomono;
    private project_restaurant.view.menu.ObjectDishPanel Takoyaki;
    private project_restaurant.view.menu.ObjectDishPanel Tempura;
    private project_restaurant.view.menu.ObjectDishPanel Yakitori;
    private project_restaurant.view.menu.BuyBottomPanel buyBottomPanel1;
    private project_restaurant.view.menu.BuyBottomPanel buyBottomPanel2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNameO1;
    private javax.swing.JLabel lblNameO2;
    private javax.swing.JLabel lblPriceO1;
    private javax.swing.JLabel lblPriceO2;
    private project_restaurant.view.menu.NavMenuPanel navMenuPanel;
    // End of variables declaration//GEN-END:variables
}
