/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_restaurant.view.menu;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author fcama
 */
public class BuyBottomPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyBottomPanel
     */
    public BuyBottomPanel() {
        initComponents();
    }
    public void listen (ActionListener controller){
        btnAddCarrito.addActionListener(controller);
    }
    
    public void mouseListen (MouseListener listen){
        btnAddCarrito.addMouseListener(listen);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddCarrito = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton compra.png"))); // NOI18N
        btnAddCarrito.setActionCommand("AddCarrito");
        btnAddCarrito.setContentAreaFilled(false);
        add(btnAddCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCarrito;
    // End of variables declaration//GEN-END:variables
}
