/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_restaurant.view.menu;

/**
 *
 * @author fcama
 */
public class MainMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenuGUI() {
        initComponents();
    }

    public MainMenuButtons getMainMenuButtons() {
        return mainMenuButtons;
    }

    public NavMenuPanel getNavMenuPanel1() {
        return navMenuPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuButtons = new project_restaurant.view.menu.MainMenuButtons();
        navMenuPanel1 = new project_restaurant.view.menu.NavMenuPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainMenuButtons.setOpaque(false);
        getContentPane().add(mainMenuButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        navMenuPanel1.setOpaque(false);
        getContentPane().add(navMenuPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private project_restaurant.view.menu.MainMenuButtons mainMenuButtons;
    private project_restaurant.view.menu.NavMenuPanel navMenuPanel1;
    // End of variables declaration//GEN-END:variables
}
