/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_restaurant.view.menu;

import project_restaurant.controller.MainMenuController;

/**
 *
 * @author fcama
 */
public class MainMenuButtons extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuButtons
     */
    public MainMenuButtons() {
        initComponents();
    }
    
    public void listen(MainMenuController mainMenuController){
        btnAppetizer.addActionListener(mainMenuController);
        btnDesserts.addActionListener(mainMenuController);
        btnDrinks.addActionListener(mainMenuController);
        btnMainCourse.addActionListener(mainMenuController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAppetizer = new javax.swing.JButton();
        btnMainCourse = new javax.swing.JButton();
        btnDesserts = new javax.swing.JButton();
        btnDrinks = new javax.swing.JButton();

        btnAppetizer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton entradas.png"))); // NOI18N
        btnAppetizer.setActionCommand("Appetizers");
        btnAppetizer.setBorderPainted(false);
        btnAppetizer.setContentAreaFilled(false);

        btnMainCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton principales.png"))); // NOI18N
        btnMainCourse.setActionCommand("MainCourse");
        btnMainCourse.setBorderPainted(false);
        btnMainCourse.setContentAreaFilled(false);

        btnDesserts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton postres.png"))); // NOI18N
        btnDesserts.setActionCommand("Desserts");
        btnDesserts.setBorderPainted(false);
        btnDesserts.setContentAreaFilled(false);

        btnDrinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton bebidas.png"))); // NOI18N
        btnDrinks.setActionCommand("Drinks");
        btnDrinks.setBorderPainted(false);
        btnDrinks.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDrinks)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAppetizer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMainCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDesserts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAppetizer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMainCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesserts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppetizer;
    private javax.swing.JButton btnDesserts;
    private javax.swing.JButton btnDrinks;
    private javax.swing.JButton btnMainCourse;
    // End of variables declaration//GEN-END:variables
}
