/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_restaurant.view.menu;

import java.awt.event.ActionListener;

/**
 *
 * @author fcama
 */
public class NavMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form NavMenu
     */
    public NavMenuPanel() {
        initComponents();
    }
    
    public void listen (ActionListener controller){
        btnAkariNav.addActionListener(controller);
        btnExitNav.addActionListener(controller);
        btnOrder.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExitNav = new javax.swing.JButton();
        btnAkariNav = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExitNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x bottom.png"))); // NOI18N
        btnExitNav.setActionCommand("X");
        btnExitNav.setContentAreaFilled(false);
        add(btnExitNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 40, 40));

        btnAkariNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/font akari.png"))); // NOI18N
        btnAkariNav.setActionCommand("Akari");
        btnAkariNav.setContentAreaFilled(false);
        add(btnAkariNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 50));

        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon orden.png"))); // NOI18N
        btnOrder.setActionCommand("Order");
        btnOrder.setContentAreaFilled(false);
        add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nav.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAkariNav;
    private javax.swing.JButton btnExitNav;
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
