/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_restaurant.view.menu;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import project_restaurant.model.PileFood;

/**
 *
 * @author fcama
 */
public class OrderTable extends javax.swing.JPanel {

    private TableRowSorter<DefaultTableModel> sorter;
    private PileFood pileFood;

    /**
     * Creates new form OrderTable
     */
    public OrderTable() {
        initComponents();
    }

//    public JTable getTblOrder() {
//        return tblOrder;
//    }
//
//    public void setTblOrder(JTable tblOrder) {
//        this.tblOrder = tblOrder;
//    }
    
//    public void setDataTable(Object[][] data) {
//    DefaultTableModel model = new DefaultTableModel(data, new String[] {"Name", "Price"});
//    tblOrder.setModel(model);
//    jScrollPane1.setViewportView(tblOrder);
//    tblOrder.setAutoCreateRowSorter(true);
//    sorter = new TableRowSorter<>(model);
//    tblOrder.setRowSorter(sorter);
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 433, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    // End of variables declaration//GEN-END:variables
}
