/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_restaurant.view.menu;

import java.awt.event.ActionListener;

/**
 *
 * @author fcama
 */
public class OrderButtonsPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderButtonsPanel
     */
    public OrderButtonsPanel() {
        initComponents();
    }
    
    public void listen(ActionListener mainMenuGUI){
        btnBuy.addActionListener(mainMenuGUI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuy = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy bottom en.png"))); // NOI18N
        btnBuy.setActionCommand("Buy");
        btnBuy.setBorderPainted(false);
        btnBuy.setContentAreaFilled(false);
        add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    // End of variables declaration//GEN-END:variables
}
