/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_restaurant.view.menu;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author fcama
 */
public class OrderGUI extends javax.swing.JFrame {

    /**
     * Creates new form OrderGUI
     */
    public OrderGUI() {
        initComponents();
    }

    public NavMenuPanel getNavMenuPanel() {
        return navMenuPanel;
    }

    public OrderButtonsPanel getOrderButtonsPanel() {
        return orderButtonsPanel;
    }

    public OrderTable getOrderTable1() {
        return orderTable1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navMenuPanel = new project_restaurant.view.menu.NavMenuPanel();
        orderButtonsPanel = new project_restaurant.view.menu.OrderButtonsPanel();
        orderTable1 = new project_restaurant.view.menu.OrderTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(navMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        orderButtonsPanel.setOpaque(false);
        getContentPane().add(orderButtonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 760, -1, -1));
        getContentPane().add(orderTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private project_restaurant.view.menu.NavMenuPanel navMenuPanel;
    private project_restaurant.view.menu.OrderButtonsPanel orderButtonsPanel;
    private project_restaurant.view.menu.OrderTable orderTable1;
    // End of variables declaration//GEN-END:variables
}
